In [112]:
from numpy import zeros as ze

In [113]:
n = 7
i,j,p = map(int,"3 3 3".split())

In [114]:
mat = ze([n,n],int)
mat[i,j] = p
mat

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [115]:
mval = p
dif=1
lT,rT,rB,lB=[i+1-p,j+1-p],[i-1+p,j+1-p],[i-1+p,j-1+p],[i+1-p,j-1+p]
print lT,rT,rB,lB

[1, 1] [5, 1] [5, 5] [1, 5]


In [118]:
def fillBox(lT,rT,rB,lB,mat,val):
    for i in range(lT[0],rT[0]+1): #fill rows 1,2,3,4,5
        #print "rows"
        #print "i,t",i,lT[1]," i,b",i,lB[1]
        mat[i,lT[1]] = val #i,1
        mat[i,lB[1]] = val #i,5
    for i in range(rT[1],rB[1]+1): #fill columns
        #print "colms"
        #print "t,i",lT[0],i," b,i",rT[0],i
        mat[lT[0],i] = val
        mat[rT[0],i] = val
    return mat
fillBox(lT,rT,rB,lB,mat,1)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 3, 0, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [121]:
print lT,rT,rB,lB
print [lT[0]+1,lT[1]+1],[rT[0]-1,rT[1]+1],[rB[0]+1,rB[1]-1],[lB[0]-1,lB[1]-1]
fillBox([lT[0]+1,lT[1]+1],[rT[0]-1,rT[1]+1],[rB[0]+1,rB[1]-1],[lB[0]-1,lB[1]-1],mat,2)

[2, 2] [4, 0] [4, 4] [2, 6]
[3, 3] [3, 1] [5, 3] [1, 5]


array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1],
       [0, 2, 2, 2, 0, 2, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])